URL_SERVICE = "https://a273d2ea-c402-4a9b-9ca9-c4ad83ee1f04.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOGS_PATH = "/api/logs/main"
USERS_PATH = "/api/db/resources/user_model.csv"
DATA_USER_PATH = "/api/v1/users/"
Main_Products_Search = "/api/v1/products/kits"