URL_SERVICE = "https://c89175c9-9949-4a72-b291-9abe177c74bf.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOGS_PATH = "/api/logs/main"
USERS_PATH = "/api/db/resources/user_model.csv"
DATA_USER_PATH = "/api/v1/users/"
Main_Products_Search = "/api/v1/products/kits"